# .pre-commit-config.yaml
# Pré-commit optimisé Python 3.11+
# Ordre important : pyupgrade -> docformatter -> isort -> black -> flake8 -> mypy

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.7
    hooks:
      - id: docformatter
        args:
          - --in-place
          - --recursive
          - --wrap-summaries=120
          - --wrap-descriptions=120
          - --make-summary-multi-line
          - --pre-summary-newline

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [--profile=black]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: [--max-line-length=120]
        exclude: ^(docker|z_old)/
        additional_dependencies: []  # ajoute ici bugbear/comprehensions si tu veux

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
    - id: mypy
      args: [--config-file=pyproject.toml]
      exclude: ^(docker|z_old)/
      additional_dependencies:
        - types-requests
        - types-PyYAML
